# Generated by Django 2.2.3 on 2019-07-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=30)),
                ('cat_descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_tipo', models.CharField(max_length=30)),
                ('comp_marca', models.CharField(max_length=30)),
                ('comp_modelo', models.CharField(max_length=30)),
                ('comp_descripcion', models.TextField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Categoria')),
                ('comp_comp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('dpn_codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dpn_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('enc_codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('enc_dni', models.CharField(max_length=8, unique=True)),
                ('enc_nombres', models.CharField(max_length=30)),
                ('enc_ape_paterno', models.CharField(max_length=30)),
                ('enc_ape_materno', models.CharField(max_length=30)),
                ('dpn_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('prg_id', models.AutoField(primary_key=True, serialize=False)),
                ('prg_nombre', models.CharField(max_length=30)),
                ('prg_version', models.CharField(max_length=30)),
                ('prg_fabrica_desarr', models.CharField(max_length=30)),
                ('prg_tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_ubicacion', models.CharField(max_length=30)),
                ('ref_piso', models.PositiveIntegerField(default=1)),
                ('ref_pabellon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('labo_id', models.AutoField(primary_key=True, serialize=False)),
                ('labo_capacidadmaquinas', models.PositiveIntegerField(default=0)),
                ('enc_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Encargado')),
                ('ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratorioProgramas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labo_prg_numPC', models.PositiveIntegerField(default=1)),
                ('labo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Laboratorio')),
                ('prg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Programa')),
            ],
            options={
                'unique_together': {('labo_id', 'prg_id', 'labo_prg_numPC')},
            },
        ),
        migrations.CreateModel(
            name='LaboratorioComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labo_cmp_numSERIE', models.CharField(max_length=10)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Componente')),
                ('labo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Laboratorio')),
            ],
            options={
                'unique_together': {('labo_id', 'comp_id', 'labo_cmp_numSERIE')},
            },
        ),
    ]
